### ISSUE TITLE
Potential Instructions for how to compile

### ISSUE THREAD

**Issue by Guitarsmasher** [Detanup01/EOS_DLL#2]
I'm wondering if you'll have instructions to compile this
Edit: I asked about dependencies but they were already on the page.

**Comment by Detanup01** [comment]
Currently you need .net 8 (and the C++ MSVC v143) and with either CLI or with help of Visual Studio you build the project

**Comment by Guitarsmasher** [comment]
Will you provide a more detailed readme like on the gbe_fork page that shows step by step on how to compile properly?

**Comment by Detanup01** [comment]
Because currently this in development and like 90% not working due to me changing and thinking how I would achieve things It would be kinda hard to change every time I do big change, but I try it
